version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: brainrocket-postgres
    environment:
      POSTGRES_DB: gaming_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - brainrocket-network

  adminer:
    image: adminer:4
    container_name: brainrocket-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - brainrocket-network

volumes:
  postgres_data:
    driver: local

networks:
  brainrocket-network:
    driver: bridge
